/usr/local/bin/python3.7 /Users/bharathdasaraju/git/python_practise/Day1_may03_2021/practices/demo8.py
Traceback (most recent call last):
  File "/Users/bharathdasaraju/git/python_practise/Day1_may03_2021/practices/demo8.py", line 13, in <module>
    test_variable = test()
  File "/Users/bharathdasaraju/git/python_practise/Day1_may03_2021/practices/demo8.py", line 6, in __init__
    main()
NameError: name 'main' is not defined

Process finished with exit code 1

